<?php

namespace Database\Seeders;

use App\Models\Book;
use Illuminate\Database\Seeder;

class BookSeeder extends Seeder
{
    public function run(): void
    {
        $books = [
            [
                'title'          => 'Laskar Pelangi',
                'author'         => 'Andrea Hirata',
                'category'       => 'Fiksi',
                'price'          => 85000,
                'original_price' => 110000,
                'rating'         => 4.8,
                'review_count'   => 2341,
                'cover'          => 'https://images.unsplash.com/photo-1760696473709-a7da66ee87a6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
                'in_stock'       => true,
                'stock'          => 45,
                'isbn'           => '978-979-1411-47-1',
                'publisher'      => 'Bentang Pustaka',
                'year'           => 2005,
                'pages'          => 534,
                'language'       => 'Indonesia',
                'description'    => 'Novel',
                'synopsis'       => 'Novel Laskar Pelangi mengisahkan tentang sepuluh anak kampung yang berjuang menuntut ilmu di sekolah yang hampir roboh di Pulau Belitung. Dengan tekad dan semangat yang membara, mereka membuktikan bahwa mimpi tidak mengenal batas ekonomi.',
            ],
            [
                'title'          => 'Atomic Habits: Perubahan Kecil yang Memberikan Hasil Luar Biasa',
                'author'         => 'James Clear',
                'category'       => 'Non-Fiksi',
                'price'          => 120000,
                'original_price' => null,
                'rating'         => 4.9,
                'review_count'   => 5892,
                'cover'          => 'https://images.unsplash.com/photo-1725869973689-425c74f79a48?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
                'in_stock'       => true,
                'stock'          => 12,
                'isbn'           => '978-602-6417-75-4',
                'publisher'      => 'Gramedia Pustaka Utama',
                'year'           => 2019,
                'pages'          => 320,
                'language'       => 'Indonesia',
                'description'    => 'Self-help / Pengembangan Diri',
                'synopsis'       => 'Atomic Habits mengajarkan cara membangun kebiasaan baik dan menghilangkan kebiasaan buruk dengan perubahan kecil namun konsisten.',
            ],
            [
                'title'          => 'Sapiens: Riwayat Singkat Umat Manusia',
                'author'         => 'Yuval Noah Harari',
                'category'       => 'Non-Fiksi',
                'price'          => 145000,
                'original_price' => null,
                'rating'         => 4.7,
                'review_count'   => 3210,
                'cover'          => 'https://images.unsplash.com/photo-1769963121626-7f1885db412c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
                'in_stock'       => true,
                'stock'          => 8,
                'isbn'           => '978-602-424-033-9',
                'publisher'      => 'Kepustakaan Populer Gramedia',
                'year'           => 2017,
                'pages'          => 484,
                'language'       => 'Indonesia',
                'description'    => 'Sejarah / Antropologi',
                'synopsis'       => 'Sapiens menelusuri perjalanan manusia dari hominid purba hingga penguasa dunia modern.',
            ],
            [
                'title'          => 'One Piece Vol. 100',
                'author'         => 'Eiichiro Oda',
                'category'       => 'Komik',
                'price'          => 35000,
                'original_price' => null,
                'rating'         => 5.0,
                'review_count'   => 8901,
                'cover'          => 'https://images.unsplash.com/photo-1588497859490-85d1c17db96d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
                'in_stock'       => true,
                'stock'          => 100,
                'isbn'           => '978-4-08-882233-5',
                'publisher'      => 'Elex Media Komputindo',
                'year'           => 2021,
                'pages'          => 200,
                'language'       => 'Indonesia',
                'description'    => 'Manga / Komik',
                'synopsis'       => 'Volume ke-100 dari manga legendaris One Piece. Luffy dan awakening Gear Fifth-nya menghadapi Kaido dalam pertarungan epik.',
            ],
            [
                'title'          => 'Matematika untuk SMA Kelas XII',
                'author'         => 'B.K. Noormandiri',
                'category'       => 'Edukasi',
                'price'          => 95000,
                'original_price' => null,
                'rating'         => 4.3,
                'review_count'   => 1205,
                'cover'          => 'https://images.unsplash.com/photo-1725869973689-425c74f79a48?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
                'in_stock'       => true,
                'stock'          => 30,
                'isbn'           => '978-979-461-902-1',
                'publisher'      => 'Erlangga',
                'year'           => 2022,
                'pages'          => 368,
                'language'       => 'Indonesia',
                'description'    => 'Buku Pelajaran',
                'synopsis'       => 'Buku pelajaran matematika komprehensif untuk siswa SMA kelas XII, sesuai kurikulum Merdeka.',
            ],
            [
                'title'          => 'Steve Jobs',
                'author'         => 'Walter Isaacson',
                'category'       => 'Biografi',
                'price'          => 130000,
                'original_price' => 160000,
                'rating'         => 4.6,
                'review_count'   => 4567,
                'cover'          => 'https://images.unsplash.com/photo-1769963121626-7f1885db412c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
                'in_stock'       => false,
                'stock'          => 0,
                'isbn'           => '978-602-03-1498-4',
                'publisher'      => 'Mizan',
                'year'           => 2011,
                'pages'          => 656,
                'language'       => 'Indonesia',
                'description'    => 'Biografi',
                'synopsis'       => 'Biografi resmi Steve Jobs berdasarkan lebih dari 40 wawancara eksklusif selama dua tahun.',
            ],
            [
                'title'          => 'Bumi',
                'author'         => 'Tere Liye',
                'category'       => 'Fiksi',
                'price'          => 79000,
                'original_price' => null,
                'rating'         => 4.5,
                'review_count'   => 3456,
                'cover'          => 'https://images.unsplash.com/photo-1760696473709-a7da66ee87a6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
                'in_stock'       => true,
                'stock'          => 25,
                'isbn'           => '978-602-291-024-6',
                'publisher'      => 'Gramedia Pustaka Utama',
                'year'           => 2014,
                'pages'          => 440,
                'language'       => 'Indonesia',
                'description'    => 'Novel Fantasi',
                'synopsis'       => 'Raib, gadis berusia 15 tahun, memiliki kemampuan menghilang dan menjelajahi dunia paralel.',
            ],
            [
                'title'          => 'Rich Dad Poor Dad',
                'author'         => 'Robert T. Kiyosaki',
                'category'       => 'Non-Fiksi',
                'price'          => 88000,
                'original_price' => null,
                'rating'         => 4.4,
                'review_count'   => 6789,
                'cover'          => 'https://images.unsplash.com/photo-1709924168698-620ea32c3488?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
                'in_stock'       => true,
                'stock'          => 18,
                'isbn'           => '978-979-685-887-1',
                'publisher'      => 'Gramedia Pustaka Utama',
                'year'           => 2000,
                'pages'          => 336,
                'language'       => 'Indonesia',
                'description'    => 'Keuangan Pribadi',
                'synopsis'       => 'Rich Dad Poor Dad mengubah paradigma tentang uang dan investasi.',
            ],
            [
                'title'          => 'Naruto Vol. 72 - Tamat',
                'author'         => 'Masashi Kishimoto',
                'category'       => 'Komik',
                'price'          => 28000,
                'original_price' => null,
                'rating'         => 4.9,
                'review_count'   => 12045,
                'cover'          => 'https://images.unsplash.com/photo-1588497859490-85d1c17db96d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
                'in_stock'       => true,
                'stock'          => 50,
                'isbn'           => '978-602-9-19523-3',
                'publisher'      => 'Elex Media Komputindo',
                'year'           => 2015,
                'pages'          => 192,
                'language'       => 'Indonesia',
                'description'    => 'Manga',
                'synopsis'       => 'Volume terakhir dari saga Naruto Uzumaki yang penuh emosi dan pengorbanan.',
            ],
            [
                'title'          => 'Biologi Molekuler untuk Mahasiswa',
                'author'         => 'Dr. Achmad Surjana',
                'category'       => 'Edukasi',
                'price'          => 175000,
                'original_price' => null,
                'rating'         => 4.1,
                'review_count'   => 312,
                'cover'          => 'https://images.unsplash.com/photo-1725869973689-425c74f79a48?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
                'in_stock'       => true,
                'stock'          => 6,
                'isbn'           => '978-602-7600-31-4',
                'publisher'      => 'Penerbit ITB',
                'year'           => 2020,
                'pages'          => 520,
                'language'       => 'Indonesia',
                'description'    => 'Buku Teks Universitas',
                'synopsis'       => 'Panduan komprehensif biologi molekuler untuk mahasiswa tingkat sarjana dan pascasarjana.',
            ],
            [
                'title'          => 'Habibie & Ainun',
                'author'         => 'B.J. Habibie',
                'category'       => 'Biografi',
                'price'          => 99000,
                'original_price' => 120000,
                'rating'         => 4.8,
                'review_count'   => 7234,
                'cover'          => 'https://images.unsplash.com/photo-1769963121626-7f1885db412c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
                'in_stock'       => true,
                'stock'          => 20,
                'isbn'           => '978-979-656-950-5',
                'publisher'      => 'THC Mandiri',
                'year'           => 2009,
                'pages'          => 326,
                'language'       => 'Indonesia',
                'description'    => 'Autobiografi / Roman',
                'synopsis'       => 'Kisah cinta abadi antara B.J. Habibie dan Ainun Besari yang ditulis langsung oleh sang Presiden.',
            ],
            [
                'title'          => 'Perahu Kertas',
                'author'         => 'Dee Lestari',
                'category'       => 'Fiksi',
                'price'          => 72000,
                'original_price' => null,
                'rating'         => 4.6,
                'review_count'   => 4123,
                'cover'          => 'https://images.unsplash.com/photo-1760696473709-a7da66ee87a6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
                'in_stock'       => true,
                'stock'          => 33,
                'isbn'           => '978-979-780-514-3',
                'publisher'      => 'Bentang Pustaka',
                'year'           => 2009,
                'pages'          => 444,
                'language'       => 'Indonesia',
                'description'    => 'Novel Romansa',
                'synopsis'       => 'Kugy dan Keenan, dua jiwa yang berbeda namun saling terhubung dalam perjalanan cinta dan pencarian jati diri.',
            ],
        ];

        foreach ($books as $book) {
            Book::create($book);
        }
    }
}
